const words = [
  { word: "infinity", hint: "These powerful stones grant immense power" },
  { word: "avengers", hint: "A team of extraordinary heroes" },
  { word: "thanos", hint: "A being obsessed with balance" },
  { word: "quantum", hint: "A realm key to time manipulation" },
  { word: "multiverse", hint: "Countless alternate realities" },
  { word: "timeline", hint: "Its disruption leads to chaos" },
  { word: "drstrange", hint: "A sorcerer supreme" },
  { word: "wanda", hint: "A witch with reality-altering powers" },
  { word: "vision", hint: "A synthetic being powered by a gem" },
  { word: "kang", hint: "A conqueror across eras" },
  { word: "portal", hint: "Magical gateways used in battle" },
  { word: "pym", hint: "A scientist behind shrinking tech" },
  { word: "soulstone", hint: "Requires a heavy price to obtain" },
  { word: "sacrifice", hint: "Iron Man's ultimate act" },
  { word: "snap", hint: "A devastating gesture" },
  { word: "loki", hint: "A trickster deity" },
  { word: "nexus", hint: "Pivotal points in reality" },
  { word: "mirror", hint: "A dimension for mystical training" },
  { word: "illuminati", hint: "A secretive council from another reality" },
  { word: "wakanda", hint: "A hidden African nation" },
  { word: "vibranium", hint: "A rare, powerful metal" },
  { word: "shield", hint: "A global defense agency" },
  { word: "odin", hint: "A wise Norse ruler" },
  { word: "asgard", hint: "A realm of gods" },
  { word: "timeheist", hint: "A plan to steal from history" },
  { word: "pymparticles", hint: "Tech enabling size alteration" },
  { word: "sanctum", hint: "A mystical stronghold" },
  { word: "titan", hint: "A desolate world of ruin" },
  { word: "mindstone", hint: "A gem granting consciousness" },
  { word: "natasha", hint: "A spy who made the ultimate choice" },
  { word: "hawkeye", hint: "A master marksman" },
  { word: "groot", hint: "A tree-like guardian" },
  { word: "quill", hint: "A cosmic adventurer" },
  { word: "mordo", hint: "A sorcerer who strayed" },
  { word: "gamora", hint: "A warrior who defied her kin" },
  { word: "stormbreaker", hint: "A god’s mighty weapon" },
  { word: "hydra", hint: "A sinister organization" },
  { word: "mjolnir", hint: "Not everyone can lift it" },
  { word: "blip", hint: "Five years felt like five seconds" },
  { word: "ultron", hint: "A creation meant to protect became destroyer" },
  { word: "jarvis", hint: "A voice that guided the genius" },
  { word: "friday", hint: "The successor to a trusted aide" },
  { word: "arc", hint: "A glowing symbol of survival" },
  { word: "hulkbuster", hint: "Armor designed for a specific green problem" },
  { word: "sokovia", hint: "A nation that paid the ultimate price" },
  { word: "peggy", hint: "A dance delayed by decades" },
  { word: "bucky", hint: "A friend worth fighting the world for" },
  { word: "zemo", hint: "He broke them from within" },
  { word: "raft", hint: "A prison for extraordinary inmates" },
  { word: "zola", hint: "A mind preserved in circuits" },
  { word: "tesseract", hint: "A cube holding infinite energy" },
  { word: "chitauri", hint: "Invaders from beyond the stars" },
  { word: "scepter", hint: "A staff that bends minds" },
  { word: "heimdall", hint: "The watchman of the rainbow bridge" },
  { word: "bifrost", hint: "A bridge of light and color" },
  { word: "mobius", hint: "An agent fascinated by variants" },
  { word: "citadel", hint: "Where all timelines converge" },
  { word: "sacred", hint: "A timeline meant to be preserved" },
  { word: "nexus", hint: "Events that branch reality" },
  { word: "antman", hint: "Size matters, but not how you think" },
  { word: "wasp", hint: "She flies where her partner shrinks" },
  { word: "quantumania", hint: "A realm of endless possibilities" },
  { word: "modok", hint: "A mind without a matching body" },
  { word: "nebula", hint: "Sister, daughter, and machine" },
  { word: "rocket", hint: "A talking guardian with big guns" },
  { word: "drax", hint: "Metaphors go over his head" },
  { word: "mantis", hint: "She feels what others feel" },
  { word: "ronan", hint: "A fanatic wielding purple power" },
  { word: "xandar", hint: "A world the Corps failed to save" },
  { word: "morag", hint: "Where the orb was hidden" },
  { word: "vormir", hint: "A planet demanding the ultimate cost" },
  { word: "redskull", hint: "A face from the past guarding souls" },
  { word: "tony", hint: "Genius, billionaire, playboy, philanthropist" },
  { word: "steve", hint: "He could do this all day" },
  { word: "thor", hint: "Still worthy after all these years" },
  { word: "bruce", hint: "The other guy finally made peace" },
  { word: "clint", hint: "A father who lost everything" },
  { word: "pepper", hint: "The CEO who suited up" },
  { word: "may", hint: "World's best aunt" },
  { word: "multiverse", hint: "With great power comes great responsibility" },
  { word: "wong", hint: "The Sorcerer Supreme who stayed" },
  { word: "ancient", hint: "One who drew power from the dark" },
  { word: "kamar", hint: "Where mystic arts are taught" },
  { word: "manhattan", hint: "Where the first great battle took place" },
  { word: "stark tower", hint: "The tallest target in the city" },
  { word: "coulson", hint: "The agent who brought them together" },
  { word: "fury", hint: "The director with secrets" },
  { word: "gauntlet", hint: "A glove to hold ultimate power" },
  { word: "shuri", hint: "The genius princess trying to save a mind" },
  { word: "dust", hint: "What half the universe became" },
];

export default words;
